### ISSUE TITLE
How can I install modules?

### ISSUE THREAD

**Issue by sheriff-rango** [owallet-io/owallet#17]
Hi,

I have downloaded your `main` branch and tried to install modules using `npm i` and `yarn`.
But I have got this error.
![image](https://user-images.githubusercontent.com/95250818/212312034-f5affd28-2b46-4d22-b2a9-846793daa2ce.png)
How can I fix this issue and install modules?

**Comment by tubackkhoa** [comment]
Please make sure your node version is >= 16.0
